import{A as E,a as L,S as q}from"./assets/vendor-wykUIgAI.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))r(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const m of n.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&r(m)}).observe(document,{childList:!0,subtree:!0});function s(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(o){if(o.ep)return;o.ep=!0;const n=s(o);fetch(o.href,n)}})();const x=document.querySelector(".hamburger-menu-button"),y=document.querySelector(".mobile-menu"),I=document.querySelector(".mobile-menu__close"),C=document.querySelectorAll(".js-menu__link");x.addEventListener("click",()=>{y.classList.add("active"),document.body.classList.add("no-scroll")});I.addEventListener("click",()=>{y.classList.remove("active"),document.body.classList.remove("no-scroll")});C.forEach(e=>{e.addEventListener("click",()=>{y.classList.remove("active"),e.getAttribute("href").substring(1),document.body.classList.remove("no-scroll")})});function M(e,t){try{const s=JSON.stringify(t);localStorage.setItem(e,s)}catch(s){console.log(s)}}function O(e){try{const t=localStorage.getItem(e);return t===null?void 0:JSON.parse(t)}catch(t){console.log(t)}}const w=document.querySelector("#switch"),b="theme",d="dark";w.addEventListener("click",B);function S(){const e=O(b)===d;e?document.body.classList.add(d):document.body.classList.remove(d),w.checked=e}S();function B(e){M(b,e.target.checked?d:""),S()}const f=document.querySelectorAll(".li-class-project"),k=document.getElementById("loadMore"),g=3;let l=3;k.addEventListener("click",P);function P(){for(let e=l;e<l+g&&e<f.length;e++)f[e].classList.remove("hidden");l+=g,l>=f.length&&(k.style.display="none")}new E(".accordion",{elementClass:"accordion-item",triggerClass:"accordion-subtitle",panelClass:"accordion-body",activeClass:"active",openOnInit:[0]});const A="https://portfolio-js.b.goit.study/api/reviews",a=document.querySelector(".left-arrow"),v=document.querySelector(".right-arrow");window.addEventListener("DOMContentLoaded",()=>{L.get(A).then(function(e){const t=document.querySelector(".swiper-wrapper");t.innerHTML=T(e.data);const s=new q(".reviews-swiper",{direction:"horizontal",loop:!1,autoHeight:!0,slidesPerView:1,spaceBetween:32,breakpoints:{1280:{slidesPerView:2}},on:{slideChange:r=>{r.isEnd?(v.disabled=!0,a.disabled=!1):r.isBeginning?a.disabled=!0:(v.disabled=!1,a.disabled=!1)}}});v.addEventListener("click",()=>{s.slideNext()}),a.addEventListener("click",()=>{s.slidePrev()})}).catch(function(e){console.error(e)})});function T(e){return e.map(({author:t,avatar_url:s,review:r})=>`<div class="swiper-slide">
           <div class="reviews-text">
           ${r}
              <div class="autor-style">
              <img class="reviews-photo" src="${s}" alt="Photo" width="40">
              <h4 class="reviews-subtitle">${t}</h4>
              </div>
           </div>
        </div>`).join("")}const u=document.querySelector(".backdrop"),D=document.querySelector(".modal-close-btn");function N(){document.body.style.overflow="hidden",u.classList.add("is-open")}function p(){document.body.style.overflow="",u.classList.remove("is-open")}D.addEventListener("click",p);u.addEventListener("click",e=>{e.target===u&&p()});document.addEventListener("keydown",e=>{e.key==="Escape"&&p()});const _=document.querySelector(".work-form"),c=document.querySelector("#user-email"),h=document.querySelector("#user-message"),i=document.querySelector(".work-form-text");_.addEventListener("submit",async e=>{e.preventDefault();const t=c.value,s=h.value;try{if((await L.post("https://portfolio-js.b.goit.study/api-docs",{email:t,message:s})).status!==200){i.textContent="Invalid email, try again",i.classList.remove("visually-hidden");return}c.value="",h.value="",document.querySelector(".work-form-icon").classList.add("visually-hidden"),N()}catch{i.textContent="Something went wrong. Please check your inputs.",i.classList.remove("visually-hidden")}});c.addEventListener("input",()=>{const e=c.checkValidity();document.querySelector(".work-form-icon").classList.toggle("visually-hidden",!e),e?(i.classList.add("visually-hidden"),c.classList.remove("invalid-text")):(i.textContent="Invalid email, try again",i.classList.remove("visually-hidden"),c.classList.add("invalid-text"))});
//# sourceMappingURL=index.js.map
